### ISSUE TITLE
Link colour not in website colour scheme

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/clarin-drupal-bootstrap-theme#14]
The colour of `<a>` elements is https://hexcolor.co/hex/153d57 - which does not appear in the visual identity document of 31 December 2020. 

Would be good to know whether this is an implementation error or an omission in the document.

**Comment by andmor-** [comment]
The color is declared [here](https://github.com/clarin-eric/clarin-drupal-bootstrap-theme/blob/main/assets/styles/utility/variables.scss#L38) and [here](https://github.com/clarin-eric/clarin-drupal-bootstrap-theme/blob/main/assets/styles/utility/variables.scss#L40)

**Comment by dietervu** [comment]
As a related issue, after consultation with some non-colourblind experts, it seems that it is difficult to distinguish the link colour from the normal text colour (#052D4D). It would be better to find a colour for links that is easier to recognize.

**Comment by dietervu** [comment]
As Robin suggested on slack, the link colour should become #0273CB (primary-blue in foundation)
