### ISSUE TITLE
Replace several CDN inclusions

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/clarin-drupal-bootstrap-theme#15]
Currently the following domains are loaded for the frontpage:

- polyfill.io
- use.fontawesome.com
- fonts.googleapis.com
- fonts.gstatic.com
- unpkg.com

Would be good to replace this by local versions, to improve the loading time and avoid all kind of user data leaks.

**Comment by andmor-** [comment]
This is on the roadmap. It is waiting for the loaded resources to stabilize as new ones appeared recently. As soon as this seems stable, I will deploy all necessary files and serve them from our servers.

**Comment by andmor-** [comment]
ATM there are 3 JS files that are still fetched from 3rd parties when users access the site:
```
https://unpkg.com/react@16.12.0/umd/react.production.min.js
https://unpkg.com/react-dom@16.12.0/umd/react-dom.production.min.js
https://polyfill.io/v3/polyfill.min.js
```

These are [hardcoded](https://git.drupalcode.org/project/sitewide_alert/-/blob/8.x-1.x/sitewide_alert.libraries.yml) as library dependencies of the Drupal [sitewide_alert](https://www.drupal.org/project/sitewide_alert) module.

So to remove them we would need to maintain a patch for this module. My initial recommendation would be to remove/replace the module (at least while we cannot supply our own JS files). But I am not fully aware about the module's specific role in our site.
