### ISSUE TITLE
Double read more link in blog view

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/clarin-drupal-bootstrap-theme#19]
https://grrr-www.clarin-dev.eu/content/sharing-knowledge-our-community shows 2 Read more links

**Comment by andmor-** [comment]
Fixed by #24

**Comment by dietervu** [comment]
The problem is indeed fixed now for https://grrr-www.clarin-dev.eu/content/sharing-knowledge-our-community

However for another page using the same mechanism (a [view](https://grrr-www.clarin-dev.eu/admin/structure/views/view/impact_stories_view) to create a block, which is included inside a landing page) the same problem occurs again:

https://grrr-www.clarin-dev.eu/content/impact-stories

The view is a duplicate of the knowledge sharing one with a only a few changes to the filters.

**Comment by dietervu** [comment]
The remainder of this issue is now separately documented as #25 upon request of Jessica
