### ISSUE TITLE
Support for external links in Learn More menu

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/clarin-drupal-bootstrap-theme#21]
One of the current items in the "Learn More" menu is a link to the Digital Humanities Course Registry. This link is supposed to open in a new window/tab and to have an [applicable icon](https://fontawesome.com/icons/external-link-alt?style=solid) next to it.

It seems the normal Drupal 8 menu links do not support this. My guess we then need to use a block instead. 

(there is a similar case for Videolectures in the same menu)

**Comment by andmor-** [comment]
Is this always and only applicable "for external links"? We could consider adding something like [this](https://drupal.stackexchange.com/a/235354) to the theme.

**Comment by andmor-** [comment]
Fixed. The icon can be added by adding the `ext-link` class to the attributes of any menu link. See [example](https://grrr-www.clarin.eu/admin/structure/menu/item/4786/edit?destination=/node/5477) for the "google docs folder" link in the "office" menu.
