### ISSUE TITLE
Secondary menu for intranet needs to be visible and collapsible

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/clarin-drupal-bootstrap-theme#22]
While there is a [block](https://grrr-www.clarin-dev.eu/admin/structure/block/manage/clarin_bootstrap_secondarymenu) for the secondary (private = only available to users belonging to certain groups) menu, it does not seem possible to have it function as earlier on: being collapsed by default but with dropdown functionality. See attached screenshot for how this looks in our current theme.
![d7-secondary-menu-intranet](https://user-images.githubusercontent.com/8073487/103881743-298b7f80-50db-11eb-8274-d5d1e06053db.jpg)

**Comment by andmor-** [comment]
I am not sure how to style it but it seems that it is now a [mega menu](https://grrr-www.clarin-dev.eu/admin/structure/we-mega-menu/menu-secondary-menu/config). I added this block and seems to work but I still don't know how to add the styles

**Comment by dietervu** [comment]
The provided fixes to the menu mainly seem to solve the issue above, but for certain pages there is a problem with the "depth" of the menus: it seems to be positioned behind the content of the page, see eg the https://grrr-www.clarin-dev.eu/content/impact-stories page - as illustrated in the following screenshot (Firefox on MacOS)

![image](https://user-images.githubusercontent.com/8073487/106923654-9ad84580-670e-11eb-9ab9-496fc52fa3f4.png)

**Comment by andmor-** [comment]
The example above is fixed but I can still see menu problems in the [front page](https://grrr-www.clarin-dev.eu/). The difference to the other pages is that the breadcrumbs block is [not displayed ](https://grrr-www.clarin-dev.eu/admin/structure/block/manage/clarin_bootstrap_breadcrumbs?destination=/admin/structure/block) in the front page.
![Screen Shot 2021-03-05 at 10 21 03](https://user-images.githubusercontent.com/6597509/110097552-7750fb00-7d9f-11eb-8283-02446cb0bc0b.png)

**Comment by andmor-** [comment]
Remaining of this issue moved to #31
