### ISSUE TITLE
Breadcrumbs for the new main menu not working

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/clarin-drupal-bootstrap-theme#23]
Breadcrumbs are not shown for any of the menu items outside the previously used Main menu ([example](https://grrr-www.clarin-dev.eu/content/resource-families)):

- nothing inside the MegaMenu gets a breadcrumb ([example](https://grrr-www.clarin-dev.eu/content/funding-new))
- but also nothing inside the "classic" submenu is shown (https://grrr-www.clarin-dev.eu/content/clarin-annual-conference)

I did enable the new Main Menu in the [menu breadcrumb config page](https://grrr-www.clarin-dev.eu/admin/config/user-interface/menu-breadcrumb) - does not seem to help.

**Comment by andmor-** [comment]
Re-sorting the menu order in [menu breadcrumb config page](https://grrr-www.clarin-dev.eu/admin/config/user-interface/menu-breadcrumb) seems to fix this. Can you confirm?

**Comment by andmor-** [comment]
It looks mostly fixed by now. Though there are still some issues to be fixed:
- your MegaMenu [example](https://grrr-www.clarin-dev.eu/content/funding-new) still does not have breadcrumbs
- When logged in I never see the breadcrumbs

**Comment by andmor-** [comment]
Breadcrumbs are now fixed using the patches in:
- https://www.drupal.org/project/menu_breadcrumb/issues/3392139
- https://www.drupal.org/project/menu_breadcrumb/issues/3230481
