### ISSUE TITLE
Template for certain pages seems to be hard-wired to the view ID

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/clarin-drupal-bootstrap-theme#25]
See eg https://grrr-www.clarin-dev.eu/content/impact-stories (wrong) vs https://grrr-www.clarin-dev.eu/content/sharing-knowledge-our-community (good) which are both based on a very similar view

we need a flexible solution: we will have more and other views in the future. Ideally we would not need to change the template all the time for that.

**Comment by andmor-** [comment]
It seems it is hard coded [here](https://github.com/clarin-eric/clarin-drupal-bootstrap-theme/blob/main/assets/styles/modules/lists.scss#L2)

**Comment by andmor-** [comment]
To test the solution proposed via Slack I assigned the CSS class `view-sharing-knowledge` to the [impact stories view](https://grrr-www.clarin-dev.eu/content/impact-stories).  This works as desired.
So I agree with the idea of renaming the class to something more generic like `grid-container-view` and then apply this class via Drupal admin UI to the views when they need it.

**Comment by andmor-** [comment]
This solution seems to work but why not just remove the extra "read more" link from [the twig template](https://github.com/clarin-eric/clarin-drupal-bootstrap-theme/blob/8216482cac2573e01afa36d552143a05cbf95305/templates/content/node--teaser-list.html.twig#L85) instead of hiding it via CSS?
