### ISSUE TITLE
Only links in content should be primary-blue

### ISSUE THREAD

**Issue by andmor-** [clarin-eric/clarin-drupal-bootstrap-theme#28]
#14 has fixed the color of the links. But this brought some undesired side effects:
1. Menu items became the new link color while they are not links. Overall we find the old color in the menu items looks better.
![Screen Shot 2021-03-05 at 16 16 25](https://user-images.githubusercontent.com/6597509/110134863-273d5d00-7dce-11eb-9371-8072f92c1346.png)
2. Menu items not inside a block are displayed in the new link color:
![Screen Shot 2021-03-05 at 16 21 30](https://user-images.githubusercontent.com/6597509/110136072-8e0f4600-7dcf-11eb-8e60-f6a125938862.png)
3. Footer links are now displayed in the same color as their section title.
![Screen Shot 2021-03-05 at 16 15 32](https://user-images.githubusercontent.com/6597509/110134750-083ecb00-7dce-11eb-9aa3-f6d997fb391c.png)
4. The links on pages of content type "Resource" (as requested in #16) also seem more natural in the old color.
![Screen Shot 2021-03-05 at 16 29 17](https://user-images.githubusercontent.com/6597509/110136414-f2320a00-7dcf-11eb-9278-9519fef9d9ce.png)

Can we make the new color for links only apply to the content section of the various pages?

**Comment by andmor-** [comment]
Mostly fixed with #34. Though I still see some issues:
1. Links in pages of content type "Resource" have a funny page top line on hover [e.g.](https://grrr-www.clarin-dev.eu/content/virtual-language-observatory)
2. Links in buttons (class `btn btn-default`) are also shown in blue which we also do not want [e.g.](https://grrr-www.clarin-dev.eu/content/data)
![Screen Shot 2021-03-16 at 11 54 53](https://user-images.githubusercontent.com/6597509/111297917-77c67d00-864e-11eb-88c0-28073bd0be32.png)

**Comment by dietervu** [comment]
1. This on-hover behaviour seems to be in line with the one in the grid overview as eg [here](https://grrr-www.clarin-dev.eu/content/test-landing-page) - guess the current behaviour is OK since most of the "resource" nodes will never be displayed in stand-alone mode
2. The button text colour indeed seems to need a change, see also the [resource family pages](https://grrr-www.clarin-dev.eu/resource-families/cmc-corpora)

**Comment by andmor-** [comment]
I am not sure about 1. For single "Resource" type pages the link underline behaves differently [e.g.](https://grrr-www.clarin-dev.eu/content/virtual-language-observatory). Here the link underline is always there as long as the mouse hovers any part of the page.
An additional problem is the whole page also shows the blue on-hover behavior (at the same time as the item itself) for anonymous users.

**Comment by andmor-** [comment]
Fixed by #37
