### ISSUE TITLE
Secondary menu overlays with primary tabs when breadcrumbs block is not displayed 

### ISSUE THREAD

**Issue by andmor-** [clarin-eric/clarin-drupal-bootstrap-theme#31]
In the site's front page the secondary user menu overlays with the primary tabs for the page. This is because the breadcrumbs block is [not displayed ](https://grrr-www.clarin-dev.eu/admin/structure/block/manage/clarin_bootstrap_breadcrumbs?destination=/admin/structure/block) in the front page.
![Screen Shot 2021-03-05 at 10 21 03](https://user-images.githubusercontent.com/6597509/110097552-7750fb00-7d9f-11eb-8283-02446cb0bc0b.png)

The vertical space neded for both elements not to overlap should be independent of the breadcrumbs block.

This ticket replaces #22 which is mostly fixed by now.

**Comment by andmor-** [comment]
No change with #34 . To reproduce:
1. Login
2. Go to the main page: https://grrr-www.clarin-dev.eu

**Comment by digitalrebelbv** [comment]
@andmor- I forgot to say that you need to change your logo to make this work. It's because your logo has too much space on the top and bottom. If you remove that it's solved. Can you do it? Or do I need to ask Robin from GRRR to do it?

**Comment by andmor-** [comment]
Fixed
