### ISSUE TITLE
Wrong menu item style for simple menu items

### ISSUE THREAD

**Issue by andmor-** [clarin-eric/clarin-drupal-bootstrap-theme#32]
When a menu item is defined directly in the menu and displayed in the megamenu (without block) it's display style should be the same as for the items inside megamenu blocks.
![Screen Shot 2021-03-11 at 11 55 37](https://user-images.githubusercontent.com/6597509/110776761-b4663300-8260-11eb-8fe5-b69567bd99f1.png)
![Screen Shot 2021-03-11 at 11 50 27](https://user-images.githubusercontent.com/6597509/110776397-4e79ab80-8260-11eb-8859-7ed5252c195e.png)

**Comment by andmor-** [comment]
Fixed with #34

**Comment by dietervu** [comment]
For the mobile view of this menu there still is a different rendering:
![image](https://user-images.githubusercontent.com/8073487/111330556-55ddf200-8670-11eb-8eee-68f0068268a6.png)

**Comment by andmor-** [comment]
Fixed by #37
